### ISSUE TITLE
Status, testing and documentation

### ISSUE THREAD

**Issue by verstrepeng** [dmslabsbr/esphome-somfy#1]
Hi,
thanks for your great project, i'm using ESPhome a lot and was realy looking for a Somfy RTS component. I would like to start testing and can give you feedback.
For me for the moment is is unclear how to get started with this project, docs are missing ;-)
Can you point me in the right direction ? Evt. i can heklp you write...
Just let me know.
#staysafe !

**Comment by dmslabsbr** [comment]
Good afternoon!

Cool your interest!

I just put some new information in this repository that may be useful to you and other users.

**Comment by verstrepeng** [comment]
Already much clearer now, this is cool !
Some questions, remarks:
- platformio.ini shouldn't that be in the folder named to your device ?
- Remote first address, why to change ? Which value to take ?
- Remote count, i have 1 somfy shade a,d 1 LED light, sou count would be 2 ? they are actually on the same RTS remote (4 channel version)
- I already have a functional remote, so i use the button on the back to put it in programming mode, right ?
- The set_code() is when i allready had an ESP an i wan't to replace it without creating a new pairing ?
Thanks for your support !

**Comment by dmslabsbr** [comment]
Hi,

- platformio.ini shouldn't that be in the folder named to your device ?
       I'dont know. Sorry! 

- Remote first address, why to change ? Which value to take ?
      The blind sometimes don't like to use the same remote code. I don't know why.
And, maybe, a neighbor have a somfy blind too, and it's good  for not have interference.
     So, at first you don't need to change the value.

- Remote count, i have 1 somfy shade a,d 1 LED light, sou count would be 2 ? they are actually on the same RTS remote (4 channel version)
   LED light? Is the led controlled by the same remote control as the blind? I don't know if it will work. Then, you tell me later.
   The RTS remote control (4 channel version) from what I read, it's like 4 RTS  one channel controls.

- I already have a functional remote, so i use the button on the back to put it in programming mode, right ?
   Yes, and then you activate the ESP programming function, using code 11.

- The set_code() is when i allready had an ESP an i wan't to replace it without creating a new pairing ?

   YES.
   But sometimes it doesn't work and you have to program it again.


- Thanks for your support !

**Comment by verstrepeng** [comment]
I am testing, but during comile, I have folloving error:
`src/RFsomfy.h:184:3: error: too many initializers for 'SomfyRts [1]'
   };
   ^
*** [/data/somfy/.pioenvs/somfy/src/main.cpp.o] Error 1`

**Comment by dmslabsbr** [comment]
even if you have 2 devices, try to maintain 3 devices in esp_somfy.yaml.
