### ISSUE TITLE
File system doent work - any ideas?

### ISSUE THREAD

**Issue by infradom** [dmslabsbr/esphome-somfy#2]
Thanks a lot for contributing  this.
I was able to program my first somfy blind, but the rolling codes do not seem to increase, so the blinds to not move after  I remove the fixed  code from the yaml file.
File system tests fail; list files returns an empty list.
I am using a D1 (esp8622MOD 12F)

Any ideas ?

Thanks,

**Comment by dmslabsbr** [comment]
Hi, how many curtains did you control?

Could you post your somfy yaml file? And step by step or what you did to get it done.

I am no longer using this system, so development is going to stop.

But, if I can, I help you.

**Comment by infradom** [comment]
Thanks,
Please find my yaml file below. I also modified the REMOTE_COUNT, REMOTE_TX_PIN pin number and REMOTE_FIRST_ADDRESS in RFsomfy.h
I created the node in esphome, validated and uploaded it. Should I have done some prior steps to create the filesystem?
Code 51 (Test file system) already fails. Code 61 (Format) does not resolve the issue.
The transmitter seems to work, I have verified this on an oscilloscope, and I did couple already some blinds (0 and 2)
Please do not spend too much time on this, especially if you are not using it anymore. I just wanted to know if I forgot a preparation step (I am new to esp; used to control my somfy blinds with raspberry through CC1101)

There is also a published SPIFFS issue with some modules that use PUYA  flash chips (manufacturer ID 0x85). Mine uses flash with manufacturer ID 0x20


esphome:
  name: somfy
  platform: ESP8266
  board: d1_mini
  includes:
    - RFsomfy.h
    - SomfyRts.h
    - SomfyRts.cpp


wifi:
  ssid: !secret Wifi_SSID
  password: !secret Wifi_Password

  ap:
    ssid: "Somfy Fallback Hotspot"
    password: "xxxxxxxxx"


web_server:
  port: 80

captive_portal:

logger:
  level: DEBUG
  esp8266_store_log_strings_in_flash: False
  baud_rate: 115200

api:
  password: "yyyyyyyyyyyyy"

ota:
  password: "yyyyyyyyyyyyy
  

cover:
- platform: custom
  lambda: |-
    std::vector<Cover *> covers;
    auto rfSomfy0 = new RFsomfy(0);
    //rfSomfy0->set_code(1); // Set initial rolling code. After it works, remove this line.
    App.register_component(rfSomfy0);
    
    auto rfSomfy1 = new RFsomfy(1);
    rfSomfy1->set_code(1);  // Set initial rolling code. After it works, remove this line.
    App.register_component(rfSomfy1);
    
    auto rfSomfy2 = new RFsomfy(2);
    //rfSomfy2->set_code(1);  // Set initial rolling code. After it works, remove this line.
    App.register_component(rfSomfy2);

    auto rfSomfy3 = new RFsomfy(3);
    rfSomfy3->set_code(1); // Set initial rolling code. After it works, remove this line.
    App.register_component(rfSomfy3);

    auto rfSomfy4 = new RFsomfy(4);
    rfSomfy4->set_code(1); // Set initial rolling code. After it works, remove this line.
    App.register_component(rfSomfy4);
    
    covers.push_back(rfSomfy0);
    covers.push_back(rfSomfy1);
    covers.push_back(rfSomfy2);
    covers.push_back(rfSomfy3);
    covers.push_back(rfSomfy4);
    return {covers};

  covers:
    - name: "Screen Groot"
      device_class: shade
      id: somfy0
    - name: "Screen Hoek"
      device_class: shade
      id: somfy1     
    - name: "Screen Zij"
      device_class: shade
      id: somfy2      
    - name: "Gordijn Groot"
      device_class: curtain
      id: somfy3
    - name: "Gordijn Hoek"
      device_class: curtain
      id: somfy4

text_sensor:
  - platform: version
    name: "RFsomfy version"
  - platform: custom
    lambda: |-
      auto rfSomfyInfo = new RFsomfyInfo();
      App.register_component(rfSomfyInfo);
      return {rfSomfyInfo};
    text_sensors:
      name: "RFsomfy info"

binary_sensor:
  - platform: status
    name: "RFsomfy status"

**Comment by dmslabsbr** [comment]
Hi, I just remember.

This line in YAML is important. It is appears to eliminate some errors.

  arduino_version: espressif8266@2.3.2

Look at my yaml file.

**Comment by infradom** [comment]
Thanks a lot, 
This seems to solve the file system error and the rolling codes seem to increase now !
I will re-pair my blinds/curtains, they do not move yet, but this is probably due to the failed test in the passt week.

Update: it works after re-pairing my blinds/curtains 

Thanks !

Jan

**Comment by dmslabsbr** [comment]
Is it works now?

**Comment by infradom** [comment]
Yes, it works very well !
Thanks a lot.
As you could see, I added a new code (16) for programming g-rail curtain motors. Thanks for merging this.
