### ISSUE TITLE
Inclination. I don't have

### ISSUE THREAD

**Issue by alnavasa** [dmslabsbr/esphome-somfy#4]
About to ordered the parts, I am wondering one thing, Would I have the inclination settings? I am going to use it for some blinds that only have up down stop function. 

Currently operating with [Smoove Origin IO remote,](https://www.ebay.es/itm/1-channel-Somfy-SMOOVE-ORIGIN-IO-remote-control-with-PURE-frame-1811066-/122039718726)
and [situo 5 io remote](http://www.remote-control-esma.com/somfy-situo-5-io-pure-1811297-remote-control/)

**This protocol (I think it is IO) won't work with this RTS system?**

My other option is to rever engineer a remote strip it out and cable it with the nodemcu/wemos

**Comment by dmslabsbr** [comment]
Hi, Sorry for the late answer.

You can try to turn ESP on to control the buttons on the controller.  It seems to be a good alternative.
