### ISSUE TITLE
error: expected type-specifier before 'RFsomfy'

### ISSUE THREAD

**Issue by jejeaure** [dmslabsbr/esphome-somfy#5]
Hi,
thanks for your project,
I'm trying to add new Somfy devices, so i have followed your procedure but i have an error while uplonding my program into my wimos D1 pro mini.
My parameters on RFsomfy.h seem to be great.

Here is my code for esp_somfy.yaml file :

`esphome:
  name: espsomfy
  platform: ESP8266
  board: d1_mini_pro

wifi:
  ssid: "xxxxxxxxxxxxxx"
  password: "xxxxxxxxxxxxxx"
  use_address: 192.168.1.10
  manual_ip:
    static_ip: 192.168.1.10
    gateway: 192.168.1.254
    subnet: 255.255.255.0

cover:
- platform: custom
  lambda: |-
    std::vector<Cover *> covers;
    auto rfSomfy0 = new RFsomfy(0);
    rfSomfy0->set_code(1);
    App.register_component(rfSomfy0);
    return {covers};

  covers:
    - name: "Blind 2"
      device_class: shade
      id: somfy0`

(i have masked my wifi ssid and password)

When y use the validate button, all is perfect. But when i use the upload button i have this following error : 

`src/main.cpp: In lambda function:
src/main.cpp:145:27: error: expected type-specifier before 'RFsomfy'
       auto rfSomfy0 = new RFsomfy(0);
                           ^
*** [/data/espsomfy/.pioenvs/espsomfy/src/main.cpp.o] Error 1
========================= [FAILED] Took 13.35 seconds =========================`

I dont know how to repair this problem.

Thanks a lot for your help

Jerome

ps : sorry for my bad english

**Comment by dmslabsbr** [comment]
Sorry for the late answer.

But as I no longer have this type of Sonfy curtain. I am no longer updating this repository. But if there's anything else I could help with, just ask.
