### ISSUE TITLE
Using esphome-somfy with CC1101?

### ISSUE THREAD

**Issue by 10bn** [dmslabsbr/esphome-somfy#6]
Hi, would it be possible to use this with an CC1101?

[https://www.amazon.de/Neuftech-Wireless-Module-Transceiver-externen/dp/B01CI01F94/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=cc1101&qid=1615056068&sr=8-3](url)

**Comment by dmslabsbr** [comment]
Sorry for the late answer.

I don't know, but I guess it won't work.
